config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts, only: [:index, :show]

  get "register", to: "admin/users#new"
  get "sign_in", to: "sessions#new"
  get "sign_out", to: "sessions#destroy"

  resources :sessions, only: [:create]
  resources :dashboards, only: [:index]
  resources :pages, only: [:show]

  namespace :admin do
    resources :posts
    resources :users
    resources :general_settings, only: [:edit, :update]
    resources :pages, except: [:show] do
      put :sort, on: :collection
    end
  end
end

app/views/admin/pages/_form.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      <% if @page.new_record? %>
         New Page
       <% else %>
         Edit Page</strong>
       <% end %>
    </h1>
  </section>

  <section class="content">

    <div class='row'>
      <div class='col-md-12'>
        <div class='box box-info'>

          <div class='box-header'>
            <% if @page.errors.any? %>
              <p>Please check the following</p>
              <ul><% @page.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            <% end %>
          </div>

          <div class='box-body pad'>
            <%= form_for [:admin, @page] do |f| %>
              <div class="form-group">
                <label>Title</label>
                <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
              </div>
              <%= f.cktext_area :body  %>
          </div>

          <div class="box-footer clearfix">
            <% if @page.new_record? %>
              <%= f.submit "Save Page", name: "draft_button", class: "btn btn-primary btn-flat" %> <br><br>
              <%= f.submit "Publish Now", name: "publish_button", class: "btn btn-success btn-flat" %>

            <% elsif @page.published? %>
              <%= f.submit "Update Page", class: "btn btn-primary btn-flat" %> <br><br>

              <%= f.submit "Unpublish and move to draft", name: "draft_button", class: "btn btn-success btn-flat" %>
            <% else %>
              <%= f.submit "Update Page", class: "btn btn-primary btn-flat" %> <br><br>

              <%= f.submit "Publish Now", name: "publish_button", class: "btn btn-success btn-flat" %>
            <% end %>
          </div>
            <% end %>

        </div>
      </div>
    </div>

  </section>
</div>

app/views/admin/pages/edit.html.erb
<%= render 'form' %>

app/views/admin/pages/index.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1>
     All Pages
    </h1>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-md-8">

        <!-- Custom Tabs -->
        <div class="nav-tabs-custom">
          <ul class="nav nav-tabs">
            <li class="active"><a href="#tab_1" data-toggle="tab">Draft Pages (<%= @pages.draft.count %>)</a></li>
            <li><a href="#tab_2" data-toggle="tab">Published Pages (<%= @pages.published.count %>)</a></li>
          </ul>

          <div class="tab-content">
            <div class="tab-pane active" id="tab_1">

                    <!-- draft pages section -->
              <div class="box">
                <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tr>
                      <th>Title</th>
                      <th>Created at</th>
                      <th>Edit/Publish</th>
                      <th>Delete</th>
                    </tr>

                    <% @pages.draft.each do |page| %>
                    <tr>
                      <td><%= page.title %></td>
                       <td><%= fix_date(page.created_at) %></td>
                       <% if !current_user.contributor? %>
                      <td><%= link_to "Edit and publish", edit_admin_page_path(page), class: "btn btn-block btn-success btn-xs" %>
                      <td><%= link_to "Delete", [:admin, page], method: :delete, data: { confirm: 'Are you sure ?' }, class: "btn btn-block btn-danger btn-xs" %></td>
                    <% else %>
                       <td data-label="Action"><%= link_to "Edit", edit_admin_page_path(page), class: "btn btn-block btn-success btn-xs" %></td>
                     <% end %>
                    </tr>
                    <% end %>
                  </table>
                </div>
              </div>
            </div>

            <div class="tab-pane" id="tab_2">
              <div class="box">
                <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tr>
                      <th>Title</th>
                      <th>Created at</th>
                      <th>Edit/Unpublish</th>
                      <th>Delete</th>
                    </tr>
                    <% @pages.published.each do |page| %>
                    <tr>
                      <td><%= link_to page.title, page %></td>
                      <td><%= fix_date(page.created_at) %></td>
                      <% if !current_user.contributor? %>
                        <td><%= link_to "Edit or unpublish", edit_admin_page_path(page), class: "btn btn-block btn-warning btn-xs" %>
                        <td><%= link_to "Delete", [:admin, page], method: :delete, data: { confirm: 'Are you sure ?' }, class: "btn btn-block btn-danger btn-xs" %></td>
                      <% else %>
                        <td><%= link_to "Edit", edit_admin_page_path(page), class: "btn btn-block btn-primary btn-xs" %></td>
                      <% end %>
                    </tr>
                  <% end %>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/pages/menu_editor.html.erb
<h1 class="content-subhead">Manage side menus (<%= @pages.header.count%>)</h1>
<table class="pure-table">
  <thead>
    <tr>
      <th>Order</th>
      <th>Title</th>
      <th>Menu Position</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @pages.published.header.each do |page| %>
    <tr class="pure-table-odd">
      <td data-label="Title">1</td>
      <td data-label="Title"><%= link_to page.title, page %></td>
      <td data-label="Created"><%= page.nav %></td>
      <% if !current_user.contributor? %>
      <td data-label="Action"><%= link_to "Edit and publish", edit_admin_page_path(page) %> | <%= link_to "Delete", [:admin, page], method: :delete, data: { confirm: 'Are you sure ?' } %></td>
      <% else %>
       <td data-label="Action"><%= link_to "Edit", edit_admin_page_path(page), class: "post-category post-category-pure" %></td>
       <% end %>
    </tr>
    <% end %>
  </tbody>
</table><br>

<%= link_to "Create a new page", new_admin_page_path, class: "button-success pure-button" %><br><br>

<h1 class="content-subhead">Manage footer menus (<%= @pages.footer.count%>)</h1>
<table class="pure-table">
  <thead>
    <tr>
      <th>Order</th>
      <th>Title</th>
      <th>Menu position</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @pages.published.footer.each do |page| %>
    <tr class="pure-table-odd">
      <td data-label="Title">2</td>
      <td data-label="Title"><%= link_to page.title, page %></td>
      <td data-label="Created"><%= page.nav %></td>
      <% if !current_user.contributor? %>
      <td data-label="Action"><%= link_to "Edit and unpublish", edit_admin_page_path(page) %> | <%= link_to "Delete", [:admin, page], method: :delete, data: { confirm: 'Are you sure ?' } %></td>
      <% else %>
       <td data-label="Action"><%= link_to "Edit", edit_admin_page_path(page), class: "post-category post-category-pure" %></td>
       <% end %>
    </tr>
    <% end %>
  </tbody>
</table><br>

<h1 class="content-subhead">Unassigned (<%= @pages.menu_undefined.count%>)</h1>
<table class="pure-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Menu position</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @pages.menu_undefined.each do |page| %>
    <tr class="pure-table-odd">
      <td data-label="Title"><%= link_to page.title, page %></td>
      <td data-label="Created"><%= page.nav %></td>
      <% if !current_user.contributor? %>
      <td data-label="Action"><%= link_to "Edit and unpublish", edit_admin_page_path(page) %> | <%= link_to "Delete", [:admin, page], method: :delete, data: { confirm: 'Are you sure ?' } %></td>
      <% else %>
       <td data-label="Action"><%= link_to "Edit", edit_admin_page_path(page), class: "post-category post-category-pure" %></td>
       <% end %>
    </tr>
    <% end %>
  </tbody>
</table><br>

app/views/admin/pages/new.html.erb
<%= render 'form' %>