config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts, only: [:index, :show]

  get "register", to: "admin/users#new"
  get "sign_in", to: "sessions#new"
  get "sign_out", to: "sessions#destroy"

  resources :sessions, only: [:create]
  resources :dashboards, only: [:index]
  resources :pages, only: [:show]

  namespace :admin do
    resources :posts
    resources :users
    resources :general_settings, only: [:edit, :update]
    resources :pages, except: [:show] do
      put :sort, on: :collection
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :require_user

  def index
    if current_user.admin? || current_user.editor?
      @posts = Post.all.order("created_at desc")
    else
      @posts = current_user.posts
    end
    @users = User.all
    @pages = Page.all
    @post = Post.new
  end
end

app/views/dashboards/_infoboxes.html.erb
<div class="small-box bg-aqua">
  <div class="inner">
    <h3><%= @posts.count %></h3>
    <p>Posts</p>
  </div>

  <div class="icon">
    <i class="ion ion-document-text"></i>
  </div>
    <%= link_to " Manage Posts ", admin_posts_path, class: "small-box-footer fa fa-arrow-circle-right" %>
  </div>
</div>

<div class="col-lg-3 col-xs-6">
  <div class="small-box bg-green">
    <div class="inner">
      <h3><%= @pages.count %></h3>
      <p>Pages</p>
    </div>
    <div class="icon">
      <i class="ion ion-ios-book-outline"></i>
    </div>
    <%= link_to " Manage Pages ", admin_pages_path, class: "small-box-footer fa fa-arrow-circle-right" %>
  </div>
</div>

<div class="col-lg-3 col-xs-6">
  <div class="small-box bg-yellow">
    <div class="inner">
      <h3><%= @users.count %></h3>
      <p>Users</p>
    </div>
    <div class="icon">
      <i class="ion-person-stalker"></i>
    </div>
    <%= link_to " Manage Users ", admin_users_path, class: "small-box-footer fa fa-arrow-circle-right" %>
  </div>
</div>

app/views/dashboards/_users.html.erb
<div class="box">
  <div class="box box-danger">

    <div class="box-header with-border">
      <h3 class="box-title">Users</h3>
    </div>

    <div class="box-body no-padding">
      <ul class="users-list clearfix">
        <% @users.each do |user| %>
          <li>
           <%= gravatar user %>
           <%= link_to user.display_name, admin_user_path(user), class: "users-list-name" %>
            <span class="users-list-date"><%= user.role %></span>
          </li>
        <% end %>
      </ul>
    </div>

    <% if current_user.admin? %>
      <div class="box-footer text-center">
        <%= link_to "Manage Users", admin_users_path %>
      </div>
    <% end %>

  </div>
</div>

app/views/dashboards/index.html.erb
<div class="content-wrapper">
  <%= render 'layouts/flash' %>

  <section class="content-header">
    <h1> Dashboard: <small> <%= current_user.display_name %></small></h1>
  </section>

  <section class="content">
    <div class="row">

      <div class="col-lg-3 col-xs-6">
        <%= render 'infoboxes' %>
    </div>


    <section class="col-lg-7">
      <div class="box">

        <!-- extract the posts index and render here, maybe move to a shared folder -->

        <div class="box-header">
          <% if @posts.draft.count == 0 %>
            <h3 class="box-title">You have not created any posts yet </h3>
          <% else %>
            <h3 class="box-title">Drafts: Needs your attention </h3>
          <% end %>
        </div>

        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <th>Title</th>
              <th>Date</th>
              <th>Author</th>
              <th style="width: 40px">Action</th>
            </tr>
            <% @posts.draft.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= fix_date(post.created_at) %></td>
                <td><%= post.user.display_name %></td>
                <% if !current_user.contributor? %>
                  <td><%= link_to "Edit and publish", edit_admin_post_path(post), class: "btn btn-block btn-primary btn-xs" %> <%= link_to "Delete", [:admin, post], method: :delete, data: { confirm: 'Are you sure ?' }, class: "btn btn-block btn-danger btn-xs" %></td>
                <% else %>
                  <td data-label="Action"><%= link_to "Edit", edit_admin_post_path(post), class: "post-category post-category-pure" %></td>
                <% end %>
              </tr>
            <% end %>
          </table>
        </div>
      </div>


      <div class='box box-info'>

        <!-- modify posts form and render it it here, maybe move it to a shared folder in admin -->

        <div class='box-header'>
          <% if @post.errors.any? %>
            <p>Please check the following</p>
            <ul><% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          <% end %>
        </div>

        <div class='box-body pad'>
          <%= form_for [:admin, @post] do |f| %>
            <div class="form-group">
              <label>Quick Post</label>
              <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
            </div>
          <%= f.cktext_area :body %>
        </div>

        <div class="box-footer clearfix">
          <% if @post.new_record? %>
            <%= f.submit "Save Post", name: "draft_button", class: "btn btn-primary btn-flat" %> <br><br>

            <% if current_user.contributor? %>
              <p>Thank you <%= current_user.display_name %>. After you save the post; an editor or admin can publish it.</p>
            <% else %>
              <%= f.submit "Publish Now", name: "publish_button", class: "btn btn-success btn-flat" %>
            <% end %>

          <% elsif @post.published? %>
            <%= f.submit "Update Post", class: "btn btn-primary btn-flat" %> <br><br>

            <%= f.submit "Unpublish and move to draft", name: "draft_button", class: "btn btn-success btn-flat" %>
          <% else %>
            <%= f.submit "Update Post", class: "btn btn-primary btn-flat" %> <br><br>

            <%= f.submit "Publish Now", name: "publish_button", class: "btn btn-success btn-flat" if !current_user.contributor? %>
          <% end %>
        </div>
          <% end %>
      </div>
    </section>


      <section class="col-lg-5">
        <%= render 'users' %>
      </section>
    </div>
  </div>
  </section>
</div>