config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts, only: [:index, :show]

  get "register", to: "admin/users#new"
  get "sign_in", to: "sessions#new"
  get "sign_out", to: "sessions#destroy"

  resources :sessions, only: [:create]
  resources :dashboards, only: [:index]
  resources :pages, only: [:show]

  namespace :admin do
    resources :posts
    resources :users
    resources :general_settings, only: [:edit, :update]
    resources :pages, except: [:show] do
      put :sort, on: :collection
    end
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <p>Please check the following</p>
  <ul><% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_footer.html.erb
<% if current_user %>
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    Enjoy the rest of your <b><%= Date::DAYNAMES[Date.today.wday] %> !</b>
  </div>

  <strong>Loong Ta: Blog management application was created with love by <a href="http://github.com/vajradog">@vajradog</a></strong>
</footer>
<% end %>

app/views/layouts/_header.html.erb
<% if current_user %>
  <div class="skin-blue sidebar-mini">

    <header class="main-header">
      <span class="logo-lg"><b><%= link_to "#{GeneralSetting.first.title}", root_path, class: "logo" %></b>
      </span>

      <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
          <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= gravatar current_user %>
                <span class="hidden-xs"><%= current_user.display_name%></span>
              </a>

              <ul class="dropdown-menu">
                <li class="user-header">
                  <%= gravatar current_user %>
                  <p>
                    <%= current_user.display_name %>
                    <small><%= current_user.email %></small>
                  </p>
                </li>

                <li class="user-footer">
                  <div class="pull-left">
                    <%= link_to "Edit profile", edit_admin_user_path(current_user), class: "btn btn-default btn-flat" %>
                  </div>
                  <div class="pull-right">
                    <%= link_to "Sign out", sign_out_path, class: "btn btn-default btn-flat" %>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
    </header>
  </div>
<% end %>

app/views/layouts/_sidenav.html.erb
<% if current_user %>
  <aside class="main-sidebar">
    <section class="sidebar">
      <ul class="sidebar-menu">

        <li class="header">MAIN NAVIGATION</li>
        <li>
          <a href="pages/widgets.html">
            <li><%= link_to " Dashboard", dashboards_path, class: "fa fa-dashboard" %>
          </a>
        </li>


        <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i>
            <span>Posts</span>
          </a>
          <ul class="treeview-menu">
            <li><%= link_to " New Post", new_admin_post_path, class: "fa fa-circle-o" %></li>
            <li><%= link_to " All Posts", admin_posts_path, class: "fa fa-circle-o" %></li>
          </ul>
        </li>


        <li class="treeview">
          <a href="#">
            <i class="fa fa-folder"></i>
            <span>Pages</span>
          </a>
          <ul class="treeview-menu">
            <li><%= link_to " New Page", new_admin_page_path, class: "fa fa-circle-o" %></li>
            <li><%= link_to " All Pages", admin_pages_path, class: "fa fa-circle-o" %></li>
          </ul>
        </li>


        <li class="treeview">
          <a href="#">
            <i class="fa fa-th"></i>
            <span>Appearances</span>
          </a>
          <ul class="treeview-menu">
            <li><%= link_to " General Settings", edit_admin_general_setting_path(GeneralSetting.first), class: "fa fa-circle-o" %></li>
            <!-- <li><a href="menu.html"><i class="fa fa-circle-o"></i>Menu</a></li> -->
          </ul>
        </li>

        <li class="treeview">
          <a href="#">
            <i class="fa fa-users"></i>
            <span>Users</span>
          </a>
          <ul class="treeview-menu">
            <li><%= link_to " New User", new_admin_user_path, class: "fa fa-circle-o" %></li>
            <li><%= link_to " All User", admin_users_path, class: "fa fa-circle-o" %></li>
          </ul>
        </li>


        <!--
        <li class="header">Extras</li>
        <li><a href=""><i class="fa fa-book"></i> <span>Documentation</span></a></li> -->

      </ul>
    </section>
  </aside>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= GeneralSetting.first.title %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <link href="/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <link href="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div data-pjax-container>
      <div class="wrapper">
        <%= render 'layouts/header'%>
        <%= render 'layouts/sidenav' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </div>

    <script src="/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js" type="text/javascript"></script>
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <script src="/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
    <script src='/plugins/fastclick/fastclick.min.js'></script>
    <script src="/dist/js/app.min.js" type="text/javascript"></script>
    <script src="/dist/js/pages/dashboard.js" type="text/javascript"></script>


    <script src="https://cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
    <script type="text/javascript">
      $(function () {
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace('editor1');
        //bootstrap WYSIHTML5 - text editor
        $(".textarea").wysihtml5();
      });
    </script>
  </body>
</html>

app/views/layouts/super-simple.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= GeneralSetting.first.title %></title>
    <%= stylesheet_link_tag    'super-simple', media: 'all' %>
    <link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <%= yield %>
  </body>
</html>